name: reactive_controller
description: A new way to extract/group/reuse common logic of StatefulWidget. Think of them like React hooks but for and of flutter.
version: 1.0.0-alpha
repository: https://github.com/HosamHasanRamadan/reactive_controller

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
